@Tradof.Api_HostAddress = https://localhost:7159/api

POST {{Tradof.Api_HostAddress}}/Account/addadmin
Content-Type: application/json
{
  "fullName": "Ali Mohamed",
  "phoneNumber": "01094211654",
  "email": "ali@example.com",
  "password": "iop[5",
  "confirmPassword": "iop[5"
}